# Generated by Django 5.1 on 2024-08-29 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('text', models.TextField(help_text='Enter your article text.')),
                ('pub_date', models.DateTimeField(blank=True, null=True, verbose_name='date published')),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
                ('is_show', models.BooleanField(default=True)),
            ],
        ),
    ]
