# Generated by Django 5.1 on 2024-08-29 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_alter_article_pub_date_alter_article_updated_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('age', models.IntegerField(default=0)),
                ('website_url', models.URLField()),
                ('score', models.FloatField()),
                ('score_2', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
        ),
    ]
