# Generated by Django 5.1 on 2024-09-08 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(default=4, max_length=100),
            preserve_default=False,
        ),
    ]
