# Generated by Django 5.1 on 2024-10-04 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0010_alter_article_auther_alter_article_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['age']},
        ),
    ]
