# Generated by Django 5.1 on 2024-10-04 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0011_alter_person_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['age'], 'verbose_name': 'شخص', 'verbose_name_plural': 'اشخاص'},
        ),
    ]
