# Generated by Django 5.1 on 2024-10-07 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0013_alter_article_options_article_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='category',
            new_name='categoreis',
        ),
    ]
